### ISSUE TITLE
Slider bug

### ISSUE THREAD

**Issue by WSSDude** [gameBear/olcPGEX_UI#1]
If you press slider and while it being pressed you leave window, you release mouse button and return to window, slider is still moving after mouse.

**Comment by gameBear** [comment]
Thank you, i had not seen the current error and will see if i can get a fix in with the text field overhaul set for this comming week.

**Comment by gameBear** [comment]
> If you press slider and while it being pressed you leave window, you release mouse button and return to window, slider is still moving after mouse.

A fix could not be found in time for this update, I will continue to look into it.
another bug with stepping sliders was resolved.
