### ISSUE TITLE
Text field doesn't accept comma, period, etc.

### ISSUE THREAD

**Issue by WSSDude** [gameBear/olcPGEX_UI#2]
Text field doesn't accept comma, period and few other symbols from my tests of this.
I don't know if this is intentional or not... But judging by the name TextField, I would assume I can put any string there.

**Comment by WSSDude** [comment]
OK, I found out what can be done at least related to those few chars I need ('.', '-', '+').
By adding these lines to definition of `lGetLetterPressed()` of TextField class, I was able to get those symbols working (could have done that before I used sliders...)

```
        if (pge->GetKey(Key::NP_DECIMAL).bPressed) return '.';
        if (pge->GetKey(Key::NP_SUB).bPressed) return '-';
        if (pge->GetKey(Key::NP_ADD).bPressed) return '+';
```

I added them as first lines of that particular function.

**Comment by gameBear** [comment]
Thank you for all the feedback.
Im currently working on an overhaul of the text input, with and added characters, including decimal, minus, plus, multiplikation and division are among the things ill add.
Update is expected to be up in the comming week.

Thanks for the feedback.

**Comment by gameBear** [comment]
> OK, I found out what can be done at least related to those few chars I need ('.', '-', '+').
> By adding these lines to definition of `lGetLetterPressed()` of TextField class, I was able to get those symbols working (could have done that before I used sliders...)
> 
> ```
>         if (pge->GetKey(Key::NP_DECIMAL).bPressed) return '.';
>         if (pge->GetKey(Key::NP_SUB).bPressed) return '-';
>         if (pge->GetKey(Key::NP_ADD).bPressed) return '+';
> ```
> 
> I added them as first lines of that particular function.

The UI has been updated to accept the following:

standard english keyboard:
'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','0','1','2','3','4','5','6','7','8','9'

shift on standard english keyboard: 
'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',')','!','@','#','$','%','^','&','*','('

from numpad: 
'0','1','2','3','4','5','6','7','8','9','*','/','+','-','.'

as well as space.
